/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ui_h_
#define _ui_h_
//---------------------------------------------------------------------------------
#define IMG_KEYBOARD_WIDTH  384
#define IMG_KEYBOARD_HEIGHT 108

extern const unsigned char ui_keyboard_data[];
extern const int ui_keyboard_size;

//--------------------------------------------------------------------

#define FNT_MIN_CHAR 32
#define FNT_MAX_CHAR 126
#define FNT_CHAR_WIDTH 6
#define FNT_CHAR_HEIGHT 8
#define BITS_IN_BYTE 8

extern const unsigned char font[];

//---------------------------------------------------------------------------------
#endif //_ui_h_
//---------------------------------------------------------------------------------
